### ISSUE TITLE
UML Tracking 

### ISSUE THREAD

**Issue by stanislavkaliuk** [Render-Devs/SimpleEngine#6]
- [x] Find a correct C++ UML program / addon
 - [x] Weekly standup (merge session)
 - [x] Transfer rules to wiki

**Comment by stanislavkaliuk** [comment]
I prefer to use free Drawio. Easy to use and extend
